server:
  http_listen_port: 
  grpc_listen_port: 

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:/loki/api/v/push

scrape_configs:
  - job_name: system
    static_configs:
    - targets:
        - localhost
      labels:
        job: varlogs
        __path__: /var/log/*log