- name: Update and upgrade apt packages
  become: true
  apt:
    upgrade: yes
    update_cache: yes
    
- name: Install latest minimal packages
  apt:
    name:
      - jq
      - curl 
      - unzip 
      - openvpn 
      - easy-rsa 
      - avahi-daemon
    state: latest