{{- if .Values.redis.enabled }}
{{- $name := include "fleet-project.name" . -}}
{{- $ns := include "fleet-project.namespace" . -}}
{{- $redisName := include "fleet-project.redisHost" . -}}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ $redisName }}
  namespace: {{ $ns }}
  labels:
    {{- include "fleet-project.labels" . | nindent 4 }}
    app: {{ $redisName }}
spec:
  serviceName: {{ $redisName }}
  replicas: 1
  selector:
    matchLabels:
      app: {{ $redisName }}
  template:
    metadata:
      labels:
        {{- include "fleet-project.labels" . | nindent 8 }}
        app: {{ $redisName }}
    spec:
      containers:
        - name: redis
          image: {{ .Values.redis.image.repository }}:{{ .Values.redis.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - redis-server
            {{- if .Values.redis.appendonly }}
            - --appendonly
            - "yes"
            {{- end }}
            - --port
            - {{ .Values.redis.port | quote }}
            {{- if .Values.redis.requireAuth }}
            - --requirepass
            - $(REDIS_PASSWORD)
            {{- end }}
          {{- if .Values.redis.requireAuth }}
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "fleet-project.secretName" . }}
                  key: redis_password
          {{- end }}
          ports:
            - name: redis
              containerPort: {{ .Values.redis.port }}
          resources:
            {{- toYaml .Values.redis.resources | nindent 12 }}
          volumeMounts:
            - name: data
              mountPath: /data
  {{- if .Values.redis.persistence.enabled }}
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        {{- if .Values.redis.persistence.storageClass }}
        storageClassName: {{ .Values.redis.persistence.storageClass }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.redis.persistence.size }}
  {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $redisName }}
  namespace: {{ $ns }}
  labels:
    {{- include "fleet-project.labels" . | nindent 4 }}
    app: {{ $redisName }}
spec:
  selector:
    app: {{ $redisName }}
  ports:
    - name: redis
      port: {{ .Values.redis.port }}
      targetPort: {{ .Values.redis.port }}
{{- end }}
