#!/usr/bin/env python3
# Copyright 2022-2026 Huntington Applied
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
SEGA gRPC STREAMING SERVER
==============================================================================
File: src/sega/api/grpc_server.py  
Project: SEGA (Specialized Cross-Domain Deployment Platform)
Copyright: 2022-2025 FLEET
License: Apache-2.0
SEGA MODULE: gRPC Streaming Server
COMPONENT: Real-time metrics streaming service
PURPOSE: Stream deployment metrics and monitoring data to external systems
DEPENDENCIES: grpcio, protobuf, core SEGA modules

This module implements the gRPC streaming server that provides real-time
metrics streaming for deployment progress, resource usage, and health monitoring.
==============================================================================
"""

import grpc
import logging
import time
import threading
import queue
import uuid
from concurrent import futures
from typing import Dict, List, Any, Generator
from dataclasses import dataclass, field

# Import protobuf generated files (these will be generated by protoc)
try:
    from ..proto import sega_metrics_pb2
    from ..proto import sega_metrics_pb2_grpc
except ImportError:
    # Fallback for when protobuf files aren't generated yet
    sega_metrics_pb2 = None
    sega_metrics_pb2_grpc = None

from google.protobuf import timestamp_pb2, struct_pb2

# Import SEGA core components
from ..core.dependency_injection import DIContainer
from ..services.deployment_service import DeploymentService

logger = logging.getLogger(__name__)

@dataclass
class MetricSubscriber:
    """Represents a client subscription to metrics."""
    subscriber_id: str
    request: Any  # MetricsStreamRequest
    queue: queue.Queue = field(default_factory=lambda: queue.Queue(maxsize=1000))
    active: bool = True
    last_sequence: int = 0


class MetricsCollector:
    """Collects metrics from various SEGA components."""
    
    def __init__(self):
        self.container = DIContainer.get_instance()
        self._running = False
        self._collection_thread = None
        self._metrics_queue = queue.Queue()
        
    def start(self):
        """Start metrics collection."""
        self._running = True
        self._collection_thread = threading.Thread(target=self._collect_metrics)
        self._collection_thread.daemon = True
        self._collection_thread.start()
        
    def stop(self):
        """Stop metrics collection."""
        self._running = False
        if self._collection_thread:
            self._collection_thread.join(timeout=5)
            
    def _collect_metrics(self):
        """Background thread to collect metrics."""
        while self._running:
            try:
                # Collect deployment metrics
                self._collect_deployment_metrics()
                
                # Collect resource metrics
                self._collect_resource_metrics()
                
                # Collect health metrics
                self._collect_health_metrics()
                
                # Sleep for a short interval
                time.sleep(1)
                
            except Exception as e:
                logger.error(f"Error collecting metrics: {e}")
                
    def _collect_deployment_metrics(self):
        """Collect deployment progress metrics."""
        try:
            deployment_service = self.container.get(DeploymentService)
            # In a real implementation, we'd get active deployments
            # For now, this is a placeholder
            pass
        except Exception as e:
            logger.debug(f"Could not collect deployment metrics: {e}")
            
    def _collect_resource_metrics(self):
        """Collect resource usage metrics."""
        try:
            import psutil
            
            # CPU usage
            cpu_percent = psutil.cpu_percent(interval=0.1)
            self._emit_resource_metric("cpu", "percentage", cpu_percent)
            
            # Memory usage
            memory = psutil.virtual_memory()
            self._emit_resource_metric("memory", "percentage", memory.percent)
            
            # Disk usage
            disk = psutil.disk_usage('/')
            self._emit_resource_metric("disk", "percentage", disk.percent)
            
        except Exception as e:
            logger.debug(f"Could not collect resource metrics: {e}")
            
    def _collect_health_metrics(self):
        """Collect service health metrics."""
        try:
            # Check various service health statuses
            services = ["api", "deployment", "monitoring", "hardware"]
            for service in services:
                # In a real implementation, check actual service health
                self._emit_health_metric(service, is_healthy=True)
        except Exception as e:
            logger.debug(f"Could not collect health metrics: {e}")
            
    def _emit_resource_metric(self, resource_type: str, unit: str, value: float):
        """Emit a resource metric."""
        if not sega_metrics_pb2:
            return
            
        metric = sega_metrics_pb2.MetricEvent(
            event_id=str(uuid.uuid4()),
            type=sega_metrics_pb2.METRIC_TYPE_RESOURCE_USAGE,
            timestamp=timestamp_pb2.Timestamp(seconds=int(time.time())),
            source="sega-metrics-collector",
            resource=sega_metrics_pb2.ResourceMetric(
                resource_id=f"system-{resource_type}",
                resource_type=resource_type,
                usage_percentage=value,
                timestamp=timestamp_pb2.Timestamp(seconds=int(time.time()))
            )
        )
        self._metrics_queue.put(metric)
        
    def _emit_health_metric(self, service_name: str, is_healthy: bool):
        """Emit a health metric."""
        if not sega_metrics_pb2:
            return
            
        metric = sega_metrics_pb2.MetricEvent(
            event_id=str(uuid.uuid4()),
            type=sega_metrics_pb2.METRIC_TYPE_SERVICE_HEALTH,
            timestamp=timestamp_pb2.Timestamp(seconds=int(time.time())),
            source="sega-metrics-collector",
            health=sega_metrics_pb2.HealthMetric(
                service_name=f"sega-{service_name}",
                service_version="0.1.0",
                is_healthy=is_healthy,
                timestamp=timestamp_pb2.Timestamp(seconds=int(time.time()))
            )
        )
        self._metrics_queue.put(metric)
        
    def get_metrics(self, timeout: float = 0.1) -> List[Any]:
        """Get collected metrics."""
        metrics = []
        deadline = time.time() + timeout
        
        while time.time() < deadline:
            try:
                metric = self._metrics_queue.get(timeout=0.01)
                metrics.append(metric)
            except queue.Empty:
                break
                
        return metrics


class Metricservicer:
    """gRPC service implementation for metrics streaming."""
    
    def __init__(self):
        self.subscribers: Dict[str, MetricSubscriber] = {}
        self.metrics_collector = MetricsCollector()
        self._distribution_thread = None
        self._running = False
        
    def start(self):
        """Start the metrics service."""
        self._running = True
        self.metrics_collector.start()
        self._distribution_thread = threading.Thread(target=self._distribute_metrics)
        self._distribution_thread.daemon = True
        self._distribution_thread.start()
        logger.info("Metrics service started")
        
    def stop(self):
        """Stop the metrics service."""
        self._running = False
        self.metrics_collector.stop()
        if self._distribution_thread:
            self._distribution_thread.join(timeout=5)
        logger.info("Metrics service stopped")
        
    def _distribute_metrics(self):
        """Background thread to distribute metrics to subscribers."""
        while self._running:
            try:
                # Get new metrics
                metrics = self.metrics_collector.get_metrics(timeout=0.5)
                
                if metrics:
                    # Distribute to all active subscribers
                    for subscriber in list(self.subscribers.values()):
                        if subscriber.active:
                            for metric in metrics:
                                if self._should_send_metric(metric, subscriber.request):
                                    try:
                                        subscriber.queue.put(metric, timeout=0.1)
                                    except queue.Full:
                                        logger.warning(f"Subscriber {subscriber.subscriber_id} queue full")
                                        
            except Exception as e:
                logger.error(f"Error distributing metrics: {e}")
                
    def _should_send_metric(self, metric: Any, request: Any) -> bool:
        """Check if a metric should be sent based on filters."""
        if not sega_metrics_pb2 or not request:
            return True
            
        # Check metric type filter
        if request.metric_types and metric.type not in request.metric_types:
            return False
            
        # Check project ID filter
        if request.project_ids and metric.project_id not in request.project_ids:
            return False
            
        # Check tag filters
        if request.tag_filters:
            for key, value in request.tag_filters.items():
                if metric.tags.get(key) != value:
                    return False
                    
        return True
        
    def StreamMetrics(self, request, context) -> Generator[Any, None, None]:
        """Stream metrics to client."""
        if not sega_metrics_pb2:
            context.abort(grpc.StatusCode.UNIMPLEMENTED, "gRPC not properly configured")
            return
            
        subscriber_id = str(uuid.uuid4())
        subscriber = MetricSubscriber(
            subscriber_id=subscriber_id,
            request=request
        )
        
        self.subscribers[subscriber_id] = subscriber
        logger.info(f"New metrics subscriber: {subscriber_id}")
        
        try:
            batch_events = []
            last_flush = time.time()
            
            while context.is_active() and subscriber.active:
                try:
                    # Get metrics from subscriber queue
                    timeout = 0.1
                    if request.flush_interval_ms:
                        timeout = min(timeout, request.flush_interval_ms / 1000.0)
                        
                    metric = subscriber.queue.get(timeout=timeout)
                    batch_events.append(metric)
                    
                    # Check if we should send a batch
                    should_flush = False
                    if request.batch_size and len(batch_events) >= request.batch_size:
                        should_flush = True
                    elif request.flush_interval_ms:
                        if (time.time() - last_flush) * 1000 >= request.flush_interval_ms:
                            should_flush = True
                            
                    if should_flush and batch_events:
                        # Create and yield batch
                        subscriber.last_sequence += 1
                        batch = sega_metrics_pb2.MetricEventBatch(
                            events=batch_events,
                            batch_sequence=subscriber.last_sequence,
                            batch_timestamp=timestamp_pb2.Timestamp(seconds=int(time.time()))
                        )
                        yield batch
                        
                        batch_events = []
                        last_flush = time.time()
                        
                except queue.Empty:
                    # Check for flush timeout
                    if request.flush_interval_ms and batch_events:
                        if (time.time() - last_flush) * 1000 >= request.flush_interval_ms:
                            subscriber.last_sequence += 1
                            batch = sega_metrics_pb2.MetricEventBatch(
                                events=batch_events,
                                batch_sequence=subscriber.last_sequence,
                                batch_timestamp=timestamp_pb2.Timestamp(seconds=int(time.time()))
                            )
                            yield batch
                            
                            batch_events = []
                            last_flush = time.time()
                            
        finally:
            # Clean up subscriber
            subscriber.active = False
            del self.subscribers[subscriber_id]
            logger.info(f"Metrics subscriber disconnected: {subscriber_id}")
            
    def PushMetric(self, request, context) -> Any:
        """Push a single metric (for testing)."""
        if not sega_metrics_pb2:
            context.abort(grpc.StatusCode.UNIMPLEMENTED, "gRPC not properly configured")
            return struct_pb2.Struct()
            
        # Distribute to all subscribers
        for subscriber in self.subscribers.values():
            if subscriber.active and self._should_send_metric(request, subscriber.request):
                try:
                    subscriber.queue.put(request, timeout=0.1)
                except queue.Full:
                    pass
                    
        # Return success response
        response = struct_pb2.Struct()
        response["status"] = "success"
        response["event_id"] = request.event_id
        return response
        
    def GetMetricSnapshot(self, request, context) -> Any:
        """Get current metric snapshot."""
        if not sega_metrics_pb2:
            context.abort(grpc.StatusCode.UNIMPLEMENTED, "gRPC not properly configured")
            return None
            
        # Collect current metrics
        metrics = self.metrics_collector.get_metrics(timeout=1.0)
        
        # Filter based on request
        filtered_metrics = []
        for metric in metrics:
            if self._should_send_metric(metric, request):
                filtered_metrics.append(metric)
                
        # Return as batch
        batch = sega_metrics_pb2.MetricEventBatch(
            events=filtered_metrics,
            batch_sequence=1,
            batch_timestamp=timestamp_pb2.Timestamp(seconds=int(time.time()))
        )
        return batch


def create_grpc_server(port: int = 50051) -> grpc.Server:
    """Create and configure the gRPC server."""
    if not sega_metrics_pb2_grpc:
        logger.error("gRPC protobuf files not generated. Run: python -m grpc_tools.protoc")
        return None
        
    # Create server with thread pool
    server = grpc.server(
        futures.ThreadPoolExecutor(max_workers=10),
        options=[
            ('grpc.max_send_message_length', 10 * 1024 * 1024),  # 10MB
            ('grpc.max_receive_message_length', 10 * 1024 * 1024),  # 10MB
        ]
    )
    
    # Create and add servicer
    servicer = Metricservicer()
    
    # Create the actual gRPC servicer class dynamically
    class MetricserviceServicer(sega_metrics_pb2_grpc.MetricserviceServicer):
        def StreamMetrics(self, request, context):
            return servicer.StreamMetrics(request, context)
            
        def PushMetric(self, request, context):
            return servicer.PushMetric(request, context)
            
        def GetMetricSnapshot(self, request, context):
            return servicer.GetMetricSnapshot(request, context)
    
    # Add servicer to server
    sega_metrics_pb2_grpc.add_MetricserviceServicer_to_server(
        MetricserviceServicer(), server
    )
    
    # Bind to port
    server.add_insecure_port(f'[::]:{port}')
    
    # Start metrics collection
    servicer.start()
    
    # Store servicer reference for cleanup
    server._metrics_servicer = servicer
    
    return server


def start_grpc_server(port: int = 50051):
    """Start the gRPC streaming server."""
    server = create_grpc_server(port)
    if not server:
        logger.error("Failed to create gRPC server")
        return
        
    server.start()
    logger.info(f"gRPC metrics streaming server started on port {port}")
    
    try:
        # Keep server running
        while True:
            time.sleep(86400)  # Sleep for a day
    except KeyboardInterrupt:
        logger.info("Shutting down gRPC server...")
        if hasattr(server, '_metrics_servicer'):
            server._metrics_servicer.stop()
        server.stop(grace=5)
        logger.info("gRPC server stopped")


if __name__ == "__main__":
    # For testing
    logging.basiconfig(level=logging.INFO)
    start_grpc_server()