#!/usr/bin/env python
"""
SEGA Project Credential Unlock Utility

This script unlocks encrypted credentials for the SEGA project and writes them to .env file.
Part of the centralized credential management system.

Usage:
    python scripts/unlock_credentials.py                    # Standard unlock
    python scripts/unlock_credentials.py --import FILE      # Import credentials
    python scripts/unlock_credentials.py --validate         # Validate credentials
    python scripts/unlock_credentials.py --help             # Show help

Security:
    - Uses AES-256 encryption with PBKDF2 key derivation
    - Master password required for all operations
    - Generated .env file is automatically gitignored
    - All credential files use secure file permissions (600)
"""

import os
import sys
import json
import getpass
import argparse
from pathlib import Path
from typing import Dict, Optional

# Add workspace root to path for credential management imports
FLEET_ROOT = Path(__file__).parent.parent.parent
sys.path.insert(0, str(FLEET_ROOT))

try:
    # These would import from the central credential management system
    # For now, we'All provide stub implementations
    from scripts.manage_credentials import decrypt_project_credentials, validate_credentials
except ImportError:
    print("Warning: central credential management system not found")
    print("Expected location: ../../scripts/manage_credentials.py")
    print("Using stub implementation for development")
    
    def decrypt_project_credentials(project_name: str, master_password: str) -> Dict[str, str]:
        """Stub implementation - replace with the actual credential system"""
        return {
            # Database credentials
            "SEGA_DB_HOST": "localhost",
            "SEGA_DB_PORT": "5011",
            "SEGA_DB_NAME": "sega_dev",
            "SEGA_DB_USER": "sega",
            "SEGA_DB_PASSWORD": "dev_password_placeholder",
            "SEGA_DATABASE_URL": "postgresql://sega:dev_password_placeholder@localhost:5011/sega_dev",
            
            # AApplication secrets
            "SEGA_JWT_SECRET_KEY": "dev_jwt_secret_key_placeholder",
            "SEGA_API_KEY": "dev_api_key_placeholder",
            "SEGA_SESSION_SECRET": "dev_session_secret_placeholder",
            "SEGA_ENCRYPTION_KEY": "dev_encryption_key_placeholder",
            "SEGA_CSRF_SECRET": "dev_csrf_secret_placeholder",
            "DEPLOYMENT_ENGINE_SECRET": "dev_deployment_secret_placeholder",
            "HARDWARE_ACCESS_SECRET": "dev_hardware_secret_placeholder",
            
            # Shared services
            "AWS_ACCESS_KEY_ID": "dev_aws_access_key_placeholder",
            "AWS_SECRET_ACCESS_KEY": "dev_aws_secret_key_placeholder",
            "KUBERNETES_CONFIG": "/path/to/kubeconfig",
            "KUBERNETES_TOKEN": "dev_k8s_token_placeholder",
            "ANSIBLE_VAULT_PASSWORD": "dev_ansible_vault_placeholder",
            "FPGA_PROGRAMMER_KEY": "dev_fpga_key_placeholder",
            "SSH_PRIVATE_KEY": "/path/to/ssh/private/key",
            "SSH_PUBLIC_KEY": "/path/to/ssh/public/key",
            "DOCKER_REGISTRY_USER": "dev_docker_user_placeholder",
            "DOCKER_REGISTRY_PASS": "dev_docker_pass_placeholder",
            
            # SEGA-specific configurations
            "SEGA_API_HOST": "0.0.0.0",
            "SEGA_API_PORT": "3011",
            "REDIS_URL": "redis://localhost:5211",
            "TIMESCALE_URL": "postgresql://sega:dev_password_placeholder@localhost:5111/sega_timeseries",
        }
    
    def validate_credentials(project_name: str) -> bool:
        """Stub implementation - replace with the actual credential system"""
        return True

def write_env_file(credentials: Dict[str, str], env_path: Path) -> None:
    """Write credentials to .env file with secure permissions."""
    try:
        # Write credentials to .env file
        with open(env_path, 'w') as f:
            f.write("# SEGA Project Credentials\n")
            f.write("# Generated by the credential management system\n")
            f.write("# DO NOT COMMIT - This file is automatically gitignored\n\n")
            
            # Group credentials by type
            db_creds = {k: v for k, v in credentials.items() if k.startswith(('SEGA_DB_', 'DATABASE_URL', 'TIMESCALE_URL', 'REDIS_URL'))}
            app_creds = {k: v for k, v in credentials.items() if k.startswith(('SEGA_JWT_', 'SEGA_API_', 'SEGA_SESSION_', 'SEGA_ENCRYPTION_', 'SEGA_CSRF_', 'DEPLOYMENT_', 'HARDWARE_'))}
            service_creds = {k: v for k, v in credentials.items() if k.startswith(('AWS_', 'KUBERNETES_', 'ANSIBLE_', 'FPGA_', 'SSH_', 'DOCKER_'))}
            sega_config = {k: v for k, v in credentials.items() if k.startswith('SEGA_API_') or k in ['SEGA_API_HOST', 'SEGA_API_PORT']}
            
            if db_creds:
                f.write("# Database Configuration\n")
                for key, value in sorted(db_creds.items()):
                    f.write(f"{key}={value}\n")
                f.write("\n")
            
            if sega_config:
                f.write("# SEGA API Configuration\n")
                for key, value in sorted(sega_config.items()):
                    f.write(f"{key}={value}\n")
                f.write("\n")
            
            if app_creds:
                f.write("# AApplication Secrets\n")
                for key, value in sorted(app_creds.items()):
                    f.write(f"{key}={value}\n")
                f.write("\n")
            
            if service_creds:
                f.write("# Shared Services\n")
                for key, value in sorted(service_creds.items()):
                    f.write(f"{key}={value}\n")
                f.write("\n")
        
        # Set secure file permissions (600 - owner read/write only)
        os.chmod(env_path, 0o600)
        print(f" Credentials written to {env_path}")
        print(f"   File permissions set to 600 (owner read/write only)")
        
    except Exception as e:
        print(f" Failed to write .env file: {e}")
        sys.exit(1)

def unlock_credentials(import_file: Optional[Path] = None) -> None:
    """Main function to unlock credentials."""
    project_root = Path(__file__).parent.parent
    env_path = project_root / ".env"
    
    try:
        # Get master password
        master_password = getpass.getpass("Enter master password: ")
        
        if import_file:
            print(f"Importing credentials from {import_file}")
            # In real implementation, this would import from encrypted backup
            print(" Import functionality requires the full credential system")
            return
        
        print("Unlocking SEGA project credentials...")
        
        # Decrypt credentials using the credential system
        credentials = decrypt_project_credentials("SEGA", master_password)
        
        # Write to .env file
        write_env_file(credentials, env_path)
        
        print(f" Successfully unlocked {len(credentials)} credentials")
        print("   Ready for SEGA development and deployment")
        
    except KeyboardInterrupt:
        print("\n Operation cancelled by user")
        sys.exit(1)
    except Exception as e:
        print(f" Failed to unlock credentials: {e}")
        sys.exit(1)

def validate_project_credentials() -> None:
    """Validate project credentials integrity."""
    try:
        print("Validating SEGA project credentials...")
        
        is_valid = validate_credentials("SEGA")
        
        if is_valid:
            print(" Credentials are valid and properly encrypted")
        else:
            print(" Credential validation failed")
            sys.exit(1)
            
    except Exception as e:
        print(f" Validation error: {e}")
        sys.exit(1)

def main():
    """Main entry point."""
    parser = argparse.ArgumentParser(
        description="SEGA Project Credential Management Utility",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
    python scripts/unlock_credentials.py                    # Unlock credentials to .env
    python scripts/unlock_credentials.py --validate         # Validate credentials
    python scripts/unlock_credentials.py --import backup.enc # Import from backup

Security Notes:
    - Master password is required for all operations
    - Generated .env file is automatically protected with 600 permissions
    - All credential files are automatically gitignored
    - Uses AES-256 encryption with PBKDF2 key derivation
        """
    )
    
    parser.add_argument(
        "--import", 
        dest="import_file", 
        type=Path,
        help="Import credentials from encrypted backup file"
    )
    
    parser.add_argument(
        "--validate",
        action="store_true",
        help="Validate credential integrity without unlocking"
    )
    
    args = parser.parse_args()
    
    if args.validate:
        validate_project_credentials()
    else:
        unlock_credentials(args.import_file)

if __name__ == "__main__":
    main()